<?php

// Pages légales (§3.4). Les variables sont remplies à partir des paramètres du site :
// :publisher, :director, :contact, :host, :retention.
return [
    'updated' => 'Dernière mise à jour : :date',

    'legal' => [
        'title' => 'Mentions légales',
        'body' => '<h2>Éditeur</h2><p>Ce site est édité par :publisher.</p><p>Directeur de la publication : :director.</p><p>Contact : :contact.</p><h2>Hébergement</h2><p>:host</p><h2>Propriété intellectuelle</h2><p>L’ensemble des contenus de ce site (textes, logo, visuels, pictogrammes, mise en page) est la propriété de The Invest In Africa Initiative ou est utilisé avec autorisation. Toute reproduction, représentation ou adaptation sans autorisation écrite préalable est interdite. Les logos des partenaires restent la propriété de leurs titulaires respectifs.</p><h2>Crédits</h2><p>Carte de l’Afrique réalisée à partir de « SVG Maps » (World), sous licence CC BY 4.0. Carte de contact © contributeurs OpenStreetMap. Polices Montserrat, Inter et Noto Sans SC sous licence SIL Open Font License.</p>',
    ],
    'privacy' => [
        'title' => 'Politique de confidentialité',
        'body' => '<h2>Responsable du traitement</h2><p>Les données personnelles collectées sur ce site sont traitées par :publisher, joignable à l’adresse suivante : :contact.</p><h2>Données collectées</h2><p>Nous ne collectons que les données nécessaires à chaque formulaire : identité et coordonnées, informations sur votre projet ou votre intérêt, documents que vous choisissez de transmettre et votre message.</p><h2>Finalités et bases légales</h2><ul><li>Examen des projets soumis et suivi des manifestations d’intérêt — mesures précontractuelles prises à votre demande</li><li>Réponse aux messages de contact — notre intérêt légitime à vous répondre</li><li>Mesure d’audience — uniquement avec votre consentement</li></ul><h2>Destinataires</h2><p>Vos données ne sont accessibles qu’aux membres habilités de notre équipe. Un dossier de projet n’est présenté à des investisseurs qu’avec votre accord. Les données ne sont jamais vendues.</p><h2>Sécurité</h2><p>Connexions chiffrées, documents stockés hors de l’espace public du serveur et accessibles uniquement par liens temporaires, accès restreints par rôle, journalisation de chaque consultation de document confidentiel, sauvegardes quotidiennes chiffrées.</p><h2>Conservation</h2><p>Les données personnelles sont anonymisées automatiquement une fois la demande traitée, après : :retention.</p><h2>Vos droits</h2><p>Vous pouvez demander l’accès à vos données, leur rectification ou leur effacement, vous opposer à leur traitement ou demander leur portabilité en écrivant à : :contact. Vous pouvez également introduire une réclamation auprès de l’autorité de protection des données de votre pays. Ces droits s’exercent conformément à la réglementation applicable, notamment le RGPD pour les visiteurs de l’Union européenne et la loi sur la protection des informations personnelles (PIPL) pour les visiteurs de la République populaire de Chine.</p>',
    ],
    'cookies' => [
        'title' => 'Politique cookies',
        'body' => '<h2>Cookies strictement nécessaires</h2><p>Session, sécurité des formulaires (CSRF) et mémorisation de votre langue. Ils ne nécessitent pas de consentement.</p><h2>Mesure d’audience</h2><p>Google Analytics 4 n’est chargé qu’après votre consentement, avec anonymisation de l’adresse IP. Votre choix est conservé six mois. Vous pouvez le modifier à tout moment via le lien « Gestion des cookies » en bas de chaque page.</p>',
    ],
    'terms' => [
        'title' => 'Conditions d’utilisation et avertissement',
        'body' => '<h2>Objet</h2><p>Les présentes conditions encadrent l’utilisation du site de :publisher. L’accès au site vaut acceptation de ces conditions.</p><h2>Informations</h2><p>The Invest In Africa Initiative veille à publier des informations exactes et à jour, sans pouvoir garantir qu’elles soient complètes ou exemptes d’erreurs. Elles peuvent être modifiées à tout moment sans préavis.</p><h2>Avertissement relatif aux investissements</h2><p>Les opportunités présentées sur ce site sont fournies à titre d’information. Elles ne constituent ni une offre ou une sollicitation d’achat ou de souscription de titres financiers, ni un conseil en investissement, juridique ou fiscal. La publication d’opportunités d’investissement peut être encadrée par la réglementation des pays concernés. Tout investissement comporte des risques, y compris la perte du capital investi. Chaque investisseur doit procéder à sa propre analyse et consulter ses conseils avant toute décision ; The Invest In Africa Initiative ne saurait être tenue responsable des décisions prises sur la base des informations publiées.</p><h2>Projets soumis</h2><p>Les porteurs de projets attestent de l’exactitude des informations transmises et en demeurent seuls responsables. La soumission d’un projet ne garantit ni sa publication ni son financement.</p><h2>Responsabilité</h2><p>The Invest In Africa Initiative ne saurait être tenue responsable des interruptions du site, des dommages résultant de son utilisation ni du contenu des sites externes vers lesquels il renvoie.</p><h2>Droit applicable</h2><p>Les présentes conditions sont régies par le droit du pays d’établissement de The Invest In Africa Initiative. Contact : :contact.</p>',
    ],
];
