<?php

// Legal pages (§3.4). Placeholders are filled from the site settings:
// :publisher, :director, :contact, :host, :retention, :updated.
return [
    'updated' => 'Last updated: :date',

    'legal' => [
        'title' => 'Legal Notice',
        'body' => '<h2>Publisher</h2><p>This website is published by :publisher.</p><p>Publication director: :director.</p><p>Contact: :contact.</p><h2>Hosting</h2><p>:host</p><h2>Intellectual property</h2><p>All content on this website (texts, logo, visuals, pictograms, layout) is the property of The Invest In Africa Initiative or is used with permission. Any reproduction, representation or adaptation without prior written authorisation is prohibited. Partner logos remain the property of their respective owners.</p><h2>Credits</h2><p>Map of Africa based on “SVG Maps” (World), licensed under CC BY 4.0. Contact map © OpenStreetMap contributors. Typefaces Montserrat, Inter and Noto Sans SC under the SIL Open Font License.</p>',
    ],
    'privacy' => [
        'title' => 'Privacy Policy',
        'body' => '<h2>Controller</h2><p>Personal data collected on this website is processed by :publisher, which can be contacted at :contact.</p><h2>Data collected</h2><p>We only collect the data required by each form: identity and contact details, information about your project or your interest, the documents you choose to send and your message.</p><h2>Purposes and legal basis</h2><ul><li>Review of project submissions and follow-up of expressions of interest — pre-contractual measures taken at your request</li><li>Replies to contact messages — our legitimate interest in answering you</li><li>Audience measurement — only with your consent</li></ul><h2>Recipients</h2><p>Your data is accessible only to the authorised members of our team. Project files may be presented to investors only with your agreement. Data is never sold.</p><h2>Security</h2><p>Encrypted connections, documents stored outside the public space of the server and reachable only through temporary links, restricted access by role, logging of every access to confidential documents, encrypted daily backups.</p><h2>Retention</h2><p>Personal data is anonymised automatically once a request has been processed, after: :retention.</p><h2>Your rights</h2><p>You may request access to, rectification or erasure of your data, object to its processing or request its portability by writing to :contact. You may also lodge a complaint with the data protection authority of your country. These rights are exercised in accordance with the applicable regulations, including the GDPR for visitors in the European Union and the Personal Information Protection Law for visitors in the People’s Republic of China.</p>',
    ],
    'cookies' => [
        'title' => 'Cookie Policy',
        'body' => '<h2>Strictly necessary cookies</h2><p>Session, security of forms (CSRF) and memorisation of your language. They do not require consent.</p><h2>Audience measurement</h2><p>Google Analytics 4 is loaded only after your consent, with IP anonymisation. Consent is kept for six months. You can change your choice at any time using the “Cookie settings” link at the bottom of each page.</p>',
    ],
    'terms' => [
        'title' => 'Terms of Use & Investment Disclaimer',
        'body' => '<h2>Purpose</h2><p>These terms govern the use of the website of :publisher. Accessing the website implies their acceptance.</p><h2>Information</h2><p>The Invest In Africa Initiative takes care to publish accurate and up-to-date information but cannot guarantee that it is complete or free of errors. Information may be modified at any time without notice.</p><h2>Investment disclaimer</h2><p>The opportunities presented on this website are provided for information purposes only. They constitute neither an offer or solicitation to buy or subscribe to financial securities, nor investment, legal or tax advice. The publication of investment opportunities may be regulated in the countries concerned. Every investment carries risks, including the loss of the capital invested. Each investor must carry out their own analysis and consult their advisers before making a decision; The Invest In Africa Initiative cannot be held liable for decisions taken on the basis of the information published.</p><h2>Submitted projects</h2><p>Project holders certify the accuracy of the information they submit and remain solely responsible for it. Submitting a project does not guarantee its publication or its financing.</p><h2>Liability</h2><p>The Invest In Africa Initiative cannot be held liable for interruptions of the website, for damage resulting from its use or for the content of external websites to which it links.</p><h2>Applicable law</h2><p>These terms are governed by the law of the country where The Invest In Africa Initiative is established. Contact: :contact.</p>',
    ],
];
